### ISSUE TITLE
ansible-test added and deprecated platforms

### ISSUE THREAD

**Issue by mattclay** [ansible-collections/news-for-maintainers#17]
The following platforms have been added to `ansible-test`:

* Containers (`--docker`)
  * ubuntu2204
  * fedora36
* Virtual Machines (`--remote`)
  * ubuntu/22.04
  * rhel/8.6
  * rhel/9.0
  * freebsd/13.1

The following platforms have been deprecated in `ansible-test`:

* Containers (`--docker`)
  * ubuntu1804
  * fedora34
* Virtual Machines (`--remote`)
  * rhel/8.5
  * freebsd/13.0

The deprecated platforms will be removed from the `devel` version of `ansible-test` on June 23rd. Please update your test environments before then.

### Azure Pipelines Test Matrix Updates

Projects using Azure Pipelines to test against the `ansible-core` `devel` branch must be updated.

> IMPORTANT: These changes should **only** be made for the portion of the test matrix tested against the `devel` branch of `ansible-core`.

#### Checklist

- [x] community.crypto:main - Update
  - [x] Remove: ubuntu1804
  - [x] Add: ubuntu2004
- [x] community.general:stable-4 - Update
  - [x] Remove: fedora34
  - [x] Remove: ubuntu1804
  - [x] Add: fedora35
  - [x] Add: ubuntu2004
- [x] community.general:stable-5 - Update
  - [x] Remove: fedora34
  - [x] Remove: ubuntu1804
  - [x] Add: fedora35
  - [x] Add: ubuntu2004
- [x] community.general:main - Update
  - [x] Remove: fedora34
  - [x] Remove: ubuntu1804
  - [x] Add: fedora35
  - [x] Add: ubuntu2004
- [x] ansible.posix:main - Update
  - [x] Remove: fedora34
  - [x] Remove: freebsd/13.0
  - [x] Remove: rhel/8.5
  - [x] Remove: ubuntu1804
  - [x] Add: fedora36
  - [x] Add: freebsd/13.1
  - [x] Add: rhel/8.6
  - [x] Add: ubuntu2204
- [X] community.postgresql:stable-1 - Update
  - [X] Remove: fedora34
  - [X] Remove: rhel/8.5
  - [X] Add: fedora35
  - [X] Add: fedora36
  - [X] Add: rhel/8.6
- [X] community.postgresql:main - Update
  - [X] Remove: fedora34
  - [X] Remove: rhel/8.5
  - [X] Add: fedora35
  - [X] Add: fedora36
  - [X] Add: rhel/8.6
- [x] community.docker:main - Update
  - [x] Remove: ubuntu1804
  - [x] Add: ubuntu2004
- [x] community.libvirt:main - Update
  - [x] Remove: fedora34
  - [x] Remove: freebsd/13.0
  - [x] Remove: rhel/8.5
  - [x] Remove: ubuntu1804
  - [x] Add: fedora36
  - [x] Add: freebsd/13.1
  - [x] Add: rhel/8.6
  - [x] Add: ubuntu2204

**Comment by saito-hideki** [comment]
Hi @mattclay 
I have fixed CI test matrix for ansible engine devel branch in `ansible.posix`:

- [x] ansible.posix:main - Update
  - [x] Remove: fedora34
  - [x] Remove: freebsd/13.0
  - [x] Remove: rhel/8.5
  - [x] Remove: ubuntu1804
  - [x] Add: fedora36
  - [x] Add: freebsd/13.1
  - [x] Add: rhel/8.6
  - [x] Add: ubuntu2204

**Comment by csmart** [comment]
@mattclay `libvirt` collection has been updated and merged, thanks.
