### ISSUE TITLE
ansible-core devel dropping controller support for Python 3.8 

### ISSUE THREAD

**Issue by mattclay** [ansible-collections/news-for-maintainers#18]
On July 11th, the `devel` version of `ansible-core` will be updated to drop **controller** support for Python 3.8.

The `devel` version of the controller will then require Python 3.9, 3.10 or 3.11. Target Python versions are not affected.

To develop and test against **multiple** versions of `ansible-core` in the same environment, the oldest version used will determine the Python version required.

| Oldest ansible-core version used for dev/test | Use Python version |
|-|-|
| 2.14 / devel | 3.9 - 3.11 |
| 2.12 and 2.13 | 3.9 - 3.10 |
| 2.11 | 3.9 |

If you maintain a collection tested on Azure Pipelines in the Ansible org:

- Update `.azure-pipelines/azure-pipelines.yml` to use `quay.io/ansible/azure-pipelines-test-container:3.0.0`
- Remove tests for `ansible-core` versions 2.10 and earlier

If you maintain a collection tested by another CI system:

- Ensure your CI system uses a new enough Python version (see the table above)
- Remove tests for `ansible-core` versions 2.10 and earlier

The following is a checklist of collections tested on Azure Pipelines which need to update their container version. Many of these will also need to drop end-of-life versions of `ansible-core` from their test matrix.

- [x] community.rabbitmq:main
- [x] community.crypto:stable-1
- [x] community.crypto:main
- [x] community.general:stable-3
- [x] community.general:stable-4
- [x] community.general:stable-5
- [x] community.general:main
- [x] community.azure:master
- [x] hetzner.hcloud:main
- [x] ansible.posix:main
- [x] community.windows:main
- [x] community.postgresql:stable-1
- [x] community.postgresql:main
- [x] community.network:stable-3
- [x] community.network:stable-1
- [x] community.network:stable-2
- [x] community.network:stable-4
- [x] community.network:main
- [x] ansible.windows:main
- [x] community.docker:stable-1
- [x] community.docker:main
- [x] community.libvirt:main

**Comment by felixfontein** [comment]
FYI: the new container image seems to work fine with Ansible 2.9 and ansible-base 2.10 as well. What does *not* work is code coverage aggregation with Ansible 2.9.

**Comment by sivel** [comment]
This was delayed slightly, but as of now, ansible-core devel no longer supports Python 3.8 for the controller.
