### ISSUE TITLE
When is the cutoff date for Major collection changes for 7.0?

### ISSUE THREAD

**Issue by carchi8py** [ansible-collections/news-for-maintainers#23]
Not sure where to ask this.

We plan to update the major version of our collection, which is already included (netapp.ontap).  And we want to make sure that the new major version is included in 7.0. Is there a date we need to have the major version update pushed to the galaxy to be included with 7.0

I remember in the past that if you made a major version change, it wouldn't be included until the next version of major version release of Ansible (I'm assuming this is still the case).

**Comment by felixfontein** [comment]
You can always check the roadmap: https://github.com/ansible/ansible/blob/devel/docs/docsite/rst/roadmap/COLLECTIONS_7.rst

According to it, feature freeze is currently planned for 2022-11-08 (one day after the planned GA of ansible-core 2.14.0).

**Comment by mariolenz** [comment]
The [roadmap](https://docs.ansible.com/ansible/devel/roadmap/COLLECTIONS_7.html) states:

```
2022-11-07: Last day for collections to make backwards incompatible releases that will be accepted into Ansible-7.
```
