### ISSUE TITLE
ansible-core stable-2.14 branch available for testing / devel updated to 2.15.0.dev0

### ISSUE THREAD

**Issue by sivel** [ansible-collections/news-for-maintainers#24]
The `ansible-core` `stable-2.14` branch is now available for testing.

If you test your collection against `stable-X.Y` branches of `ansible-core` then you should consider adding `stable-2.14` to your testing matrix. The stable branch currently represents a pre-release version of `ansible-core`.

For additional details, consult the [release schedule from the roadmap](https://docs.ansible.com/ansible/devel/roadmap/ROADMAP_2_14.html#release-phase).

---

The `ansible-core` `devel` branch has been updated to `2.15.0.dev0`.  If you test against `devel`, you may need to copy your `tests/sanity/ignore-2.14.txt` file to `tests/sanity/ignore-2.15.txt` and run `ansible-test sanity` from `devel` and add, or address any additional failing sanity tests

**Comment by briantist** [comment]
It would be helpful in these announcements to also include (or link to) the python versions supported by the new branch.
