### ISSUE TITLE
ansible-test's pylint sanity test updated to pylint 2.17.0 on devel

### ISSUE THREAD

**Issue by felixfontein** [ansible-collections/news-for-maintainers#33]
https://github.com/ansible/ansible/pull/79878 was merged yesterday which updates pylint used by ansible-test's pylint sanity test on ansible-core's devel branch to pylint 2.16.0. This potentially causes new linting failures when you test your collection against ansible-core devel.

**Comment by mattclay** [comment]
The pylint version used by ansible-test in the devel branch has been updated to 2.17.0 in https://github.com/ansible/ansible/pull/80172/.
