### ISSUE TITLE
ansible-test `ansible-format-automatic-specification` pylint rule removed

### ISSUE THREAD

**Issue by evgeni** [ansible-collections/news-for-maintainers#35]
In https://github.com/ansible/ansible/pull/79985 the `ansible-format-automatic-specification` pylint rule was dropped.

This leads to code that currently references that rule (e.g. via `# pylint: disable=ansible-format-automatic-specification`) fail to lint with
```
unknown-option-value: Unknown option value for 'disable', expected a valid pylint message and got 'ansible-format-automatic-specification'
```

It is safe to drop the disablement if you're running `ansible-test sanity` against `devel`, but then the code might start reporting issues on stable branches.

**Comment by mattclay** [comment]
The `ansible-format-automatic-specification` rule for the `pylint` sanity test has been restored (but disabled), to allow existing inline ignores to be used. Since the rule is disabled, it will not be reported in ansible-core 2.15 (devel) or later.
