### ISSUE TITLE
💡 Idea: migrate issues to discussions and surface them to the org level

### ISSUE THREAD

**Issue by webknjaz** [ansible-collections/news-for-maintainers#39]
### Observations

This repository's README calls out the possibility to use both `Issues` and `Discussions` but does not give any guidance as to when to use each.
I feel like this contributes to the confusion in the decision making.
Moreover, when one tries to create an issue, they are presented with a selection of issue templates that are derived from the org config and have nothing to do with the purpose of this repository — every one of them is asking for Ansible/collection versions/OS/STR/etc. I've clicked through a few of the old issues and haven't found any, following said templates. This means that _every single issue creator_ was forced to clean up the template or notice that tiny [Open a blank issue.](https://github.com/ansible-collections/news-for-maintainers/issues/new) link at the bottom. FWIW, it doesn't seem like the posts here do need any templates at all.

Issues represent problems/bugs/something to be worked on in the project. But this repository seems to exist for having discussions and announcements.
Also, https://github.com/ansible-collections/news-for-maintainers/discussions/4#discussion-3845807 mentions that earlier expectation of using discussions over issues.

### Problems

I think, the current setup causes more cognitive load, than it should.

* Having two places to watch over means maintenance burden and contributor confusion. Multiple ways of doing the same thing is not good.
* Issues aren't well-fit for making announcements.

### Proposal

* [ ] Migrate issues into discussions (GH makes automatic redirects)
* [ ] Disable issues in the repository, only leave the discussions enabled
* [ ] Enable organization-level discussions, selecting this repository as their location (the discussions can't be detached from the repo)
* [ ] Make use of the existing discussion categories:
  * [ ] Announcements — only maintainers can post there
  * [ ] Q&A — allows selecting the correct response
  * [ ] Polls — has built-in interface for collecting preferred solutions with answer variants to the question being discussed
  * [ ] Show and tell — show-off (not sure if needed in this specific repo)
  * [ ] Ideas — requests to do stuff/change processes/etc.

**Comment by samccann** [comment]
Hi @webknjaz !  This is an interesting idea. Can you please include it as a comment to the existing community-topic that is up for active vote on using Discourse as a forum for Ansible. See https://github.com/ansible-community/community-topics/issues/202

I don't wish to be heavy-handed as you have some great points, but going to close this issue for now so we don't split the conversation. Thanks for the ideas!
