### ISSUE TITLE
ansible-core devel dropping controller support for Python 3.9

### ISSUE THREAD

**Issue by s-hertel** [ansible-collections/news-for-maintainers#49]
Amending https://github.com/ansible-collections/news-for-maintainers/issues/48:

On July 6th, the version of ansible-core will be updated to drop controller support for Python 3.9. The devel version of the controller will then require Python 3.10, 3.11, or 3.12. Target Python versions are not affected. To develop and test against multiple versions of ansible-core in the same environment, the oldest version used will determine the Python version required.

Oldest ansible-core version used for dev/test | Use Python version
-- | --
2.16 / devel | 3.10 - 3.12
2.14 and 2.15 | 3.10 - 3.11
2.12 and 2.13 | 3.10

If you maintain a collection tested on Azure Pipelines in the Ansible org:

* Update .azure-pipelines/azure-pipelines.yml to use quay.io/ansible/azure-pipelines-test-container:4.0.1
* Remove tests for ansible-core versions 2.11 and earlier

If you maintain a collection tested by another CI system:

* Ensure your CI system uses a new enough Python version (see the table above)
* Remove tests for ansible-core versions 2.11 and earlier

The following is a checklist of collections tested on Azure Pipelines which need to update their container version. Many of these will also need to drop end-of-life versions of ansible-core from their test matrix.

- [x] community.libvirt:main
- [x] community.postgresql:stable-2
- [x] community.postgresql:main
- [x] community.postgresql:stable-1
- [x] microsoft.ad:main
- [x] community.rabbitmq:main
- [x] community.network:main
- [x] community.network:stable-4
- [x] community.network:stable-5
- [x] ansible.windows:main
- [ ] consoledot.edgemanagement:main
- [x] community.docker:stable-2
- [x] community.docker:main
- [x] ansible.posix:main
- [x] community.windows:main
- [x] community.crypto:main
- [x] community.crypto:stable-1
- [x] community.general:stable-7
- [x] community.general:stable-6
- [x] community.general:main
- [x] community.general:stable-5
- [x] hetzner.hcloud:main

**Comment by felixfontein** [comment]
If you still need to run tests with ansible-core 2.11 or earlier, you need to run them with GHA.

For example community.general still supports Ansible 2.9+, and runs tests with EOL'ed Ansible/ansible-base/ansible-core versions with GHA, and others with AZP. The config files are as follows: https://github.com/ansible-collections/community.crypto/blob/main/.github/workflows/ansible-test.yml and https://github.com/ansible-collections/community.crypto/blob/main/.azure-pipelines/azure-pipelines.yml
