### ISSUE TITLE
ansible-core 2.17 removing target support for Python 2.7 and 3.6

### ISSUE THREAD

**Issue by sivel** [ansible-collections/news-for-maintainers#54]
Yes, you read that right!  ansible-core 2.17 will remove python 2 support completely, and finally!  In addition to removing Python 2.7 support, we will also be removing target support for Python 3.6.

The plan is to remove support for these versions during the week of October 1, 2023 in devel.  This will happen very early in the 2.17 development cycle to enable merging new functionality that depends on the removal of Python 2.7.

For more information about controller and target python support in ansible-core, please see the section starting at https://docs.ansible.com/ansible-core/devel/reference_appendices/release_and_maintenance.html#ansible-core-control-node-python-support

**Comment by felixfontein** [comment]
In case someone wants to discuss this, I've created a discussion (#55) so that the issue won't get spammed. I'm now locking this (as usual).

**Comment by felixfontein** [comment]
This has now been implemented, see #60.
