### ISSUE TITLE
ansible-test - Added RHEL 9.3 and deprecated RHEL 9.2

### ISSUE THREAD

**Issue by mkrizek** [ansible-collections/news-for-maintainers#62]
> PENDING: https://github.com/ansible/ansible/pull/82178

The following platforms have been added to ansible-test:

* Virtual Machines (`--remote`)
  * rhel/9.3

The following platforms have been deprecated in ansible-test:

* Virtual Machines (`--remote`)
  * rhel/9.2

The deprecated platforms will be removed from the `devel` version of `ansible-test` on **_November 27th_**. Please update your test environments before then.

### Azure Pipelines Test Matrix Updates

Projects using Azure Pipelines to test against the ansible-core devel branch must be updated.

> IMPORTANT: These changes should only be made for the portion of the test matrix tested against the devel branch of ansible-core.

- [x] community.postgresql:stable-1
  - [x] Replace `rhel/9.2` with `rhel/9.3`
- [x] community.postgresql:stable-2
  - [x] Replace `rhel/9.2` with `rhel/9.3`
- [x] community.postgresql:main
  - [x] Replace `rhel/9.2` with `rhel/9.3`
- [x] ansible.posix:main
  - [x] Replace `rhel/9.2` with `rhel/9.3`
- [x] community.libvirt:main
  - [x] Replace `rhel/9.2` with `rhel/9.3`
- [x] community.crypto:main
  - [x] Replace `rhel/9.2` with `rhel/9.3`
- [x] community.docker:main
  - [x] Replace `rhel/9.2` with `rhel/9.3`
- [x] community.general:stable-7
  - [x] Replace `rhel/9.2` with `rhel/9.3`
- [x] community.general:stable-8
  - [x] Replace `rhel/9.2` with `rhel/9.3`
- [x] community.general:main
  - [x] Replace `rhel/9.2` with `rhel/9.3`
- [x] ansible.ansible:devel
  - [x] Replace `rhel/9.2` with `rhel/9.3`

**Comment by gotmax23** [comment]
I copied this over to https://forum.ansible.com/t/ansible-test-added-rhel-9-3-and-deprecated-rhel-9-2/2336. Folks are also welcome to create a Github Discussion in this repo to discuss further.
