### ISSUE TITLE
 ansible-test - Added Fedora 39 and deprecated Fedora 38

### ISSUE THREAD

**Issue by Akasurde** [ansible-collections/news-for-maintainers#63]
The following platforms have been added to ansible-test:

- Containers (`--docker`)
    - fedora39
- Virtual Machines (`--remote`)
    - fedora/39

The following platforms have been deprecated in ansible-test:

- Containers (`--docker`)
    - fedora38
- Virtual Machines (`--remote`)
    - fedora/38

### Azure Pipelines Test Matrix Updates

The following collections tested with the `devel` branch of `ansible-core` should be updated:

- [x] community.postgresql:stable-1
  - [x] Replace `fedora38` with `fedora39`
- [x] community.postgresql:stable-2
  - [x] Replace `fedora38` with `fedora39`
- [x] community.postgresql:main
  - [x] Replace `fedora38` with `fedora39`
- [x] ansible.posix:main
  - [x] Replace `fedora38` with `fedora39`
- [x] community.libvirt:main
  - [x] Replace `fedora38` with `fedora39`
- [x] community.crypto:main
  - [x] Replace `fedora/38` with `fedora/39`
  - [x] Replace `fedora38` with `fedora39`
- [x] community.docker:main
  - [x] Replace `fedora38` with `fedora39`
- [x] community.general:stable-7
  - [x] Replace `fedora38` with `fedora39`
- [x] community.general:stable-8
  - [x] Replace `fedora38` with `fedora39`
- [x] community.general:main
  - [x] Replace `fedora38` with `fedora39`

**Comment by felixfontein** [comment]
I copied this over to https://forum.ansible.com/t/ansible-test-added-fedora-39-and-deprecated-fedora-38/2440. Folks are also welcome to create a Github Discussion in this repo to discuss further.
