### ISSUE TITLE
ansible-core 2.14 and 2.15 updating from FreeBSD 13.1 to 13.2

### ISSUE THREAD

**Issue by sivel** [ansible-collections/news-for-maintainers#64]
FreeBSD 13.1 has been EOL for a little over 4 months, and it appears the FreeBSD maintainers have removed the 13.1 release from their repo/mirrors.  As a result CI is failing, at a minimum for core, on the `freebsd/13.1` remotes.

We are in the process of updating these stable branches to utilize FreeBSD 13.2, and will merge them immediately once ready.

Upon completion of this update, ansible-core 2.15.8 and 2.14.13 will also be released with this change as a result of https://groups.google.com/g/ansible-announce/c/LSZW2qILvbk

**Comment by felixfontein** [comment]
I copied this over to https://forum.ansible.com/t/ansible-test-ansible-core-2-14-and-2-15-updating-from-freebsd-13-1-to-13-2/2853. Folks are also welcome to create a Github Discussion in this repo to discuss further.
