### ISSUE TITLE
ansible-test — Added macOS 14.3 and deprecated macOS 13.2

### ISSUE THREAD

**Issue by webknjaz** [ansible-collections/news-for-maintainers#65]
The `devel` version of `ansible-test` [has been updated](https://github.com/ansible/ansible/pull/82697) to include support for macOS 14.3. Collections testing against macOS should update to the new version by March 27th.

> [!IMPORTANT]
> These changes should only be made for the portion of the test matrix tested against the `devel` branch of `ansible-core`.

### Azure Pipelines Test Matrix Updates

The following collections tested with the `devel` branch of `ansible-core` should be updated:

- [x] community.crypto:main
  - [x] Replace `macos/13.2` with `macos/14.3`
- [x] community.general:main
  - [x] Replace `macos/13.2` with `macos/14.3`
- [x] community.general:stable-7
  - [x] Replace `macos/13.2` with `macos/14.3`
- [x] community.general:stable-8
  - [x] Replace `macos/13.2` with `macos/14.3`

**Comment by felixfontein** [comment]
I copied this over to https://forum.ansible.com/t/ansible-test-added-macos-14-3-and-deprecated-macos-13-2/4330.

**Comment by felixfontein** [comment]
This (`macos/13.2`) has been removed with https://github.com/ansible/ansible/pull/82291.
