### ISSUE TITLE
ansible-test - Added FreeBSD 13.3, 14.0 and deprecated 13.2

### ISSUE THREAD

**Issue by mattclay** [ansible-collections/news-for-maintainers#67]
The `devel` version of `ansible-test` has been updated to include support for FreeBSD 13.3 and 14.0. Collections testing against FreeBSD should update their test matrix by Thursday, March 28th. After that date, support for FreeBSD 13.2 will be removed.

### Azure Pipelines Test Matrix Updates

The following collections tested with the `devel` branch of `ansible-core` should be updated:

- [x] ansible.posix:main
  - [x] Replace `freebsd/13.2` with `freebsd/13.3`
- [x] community.libvirt:main
  - [x] Replace `freebsd/13.2` with `freebsd/13.3`
- [x] community.crypto:main
  - [x] Replace `freebsd/13.2` with `freebsd/13.3`
- [x] community.general:stable-7
  - [x] Replace `freebsd/13.2` with `freebsd/13.3`
- [x] community.general:stable-8
  - [x] Replace `freebsd/13.2` with `freebsd/13.3`
- [x] community.general:main
  - [x] Replace `freebsd/13.2` with `freebsd/13.3`

Additionally, the above collections should add support for `freebsd/14.0`.

**Comment by felixfontein** [comment]
Copied over to https://forum.ansible.com/t/ansible-test-added-freebsd-13-3-14-0-and-deprecated-13-2/4503 on the Forum.
