### ISSUE TITLE
ansible-test - Added Alpine 3.19 and deprecated 3(.18)

### ISSUE THREAD

**Issue by mattclay** [ansible-collections/news-for-maintainers#68]
The `devel` version of `ansible-test` has been updated to include support for Alpine 3.19. Collections testing against Alpine should update their test matrix by Thursday, March 28th. After that date, support for Alpine 3(.18) will be removed.

### Azure Pipelines Test Matrix Updates

The following collections tested with the `devel` branch of `ansible-core` should be updated:

- [x] community.crypto:main
  - [x] Replace `alpine3` with `alpine319`
  - [x] Replace `alpine/3.18` with `alpine/3.19`
- [x] community.docker:main
  - [x] Replace `alpine3` with `alpine319`
- [x] community.general:stable-7
  - [x] Replace `alpine3` with `alpine319`
  - [x] Replace `alpine/3.18` with `alpine/3.19`
- [x] community.general:stable-8
  - [x] Replace `alpine3` with `alpine319`
  - [x] Replace `alpine/3.18` with `alpine/3.19`
- [x] community.general:main
  - [x] Replace `alpine3` with `alpine319`
  - [x] Replace `alpine/3.18` with `alpine/3.19`

NOTE: Previously the Alpine container was named `alpine3` and was updated in place from one version to the next. Starting with Alpine 3.19, the container now follows the same naming convention as other containers, as is named `alpine319`.

**Comment by felixfontein** [comment]
Copied over to https://forum.ansible.com/t/ansible-test-added-alpine-3-19-and-deprecated-3-18/4508 on the Forum.
